/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontend;

import ManejadorArchivos.abrirArchivos;
import Analizador.analizador;
import Analizador.busqueda;
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.SwingConstants;
import javax.swing.text.BadLocationException;
import Tokens.errorLexico;
import Tokens.token;
/**
 *
 * @author blue
 */
public class inicioAnalizador extends javax.swing.JFrame {

    private analizador analizador = new analizador();
        
    /**
     * Creates new form analizador
     */
    public inicioAnalizador() {
        initComponents();
        
        setLocationRelativeTo(null);
        setResizable(false);
        
        numeracionArea = new JTextArea();
        jScrollPane.setRowHeaderView(mostrarNumeroFilas());      
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelGeneral = new javax.swing.JPanel();
        jPanelCentral = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane = new javax.swing.JScrollPane();
        jTextAreaEdicion = new javax.swing.JTextArea();
        jPanelResultados = new javax.swing.JPanel();
        jPanelSuperior = new javax.swing.JPanel();
        jPanelHeader = new javax.swing.JPanel();
        jPanelBotones = new javax.swing.JPanel();
        jPanelBuscar = new javax.swing.JPanel();
        jTextFieldBuscar = new javax.swing.JTextField();
        jButtonBuscar = new javax.swing.JButton();
        jButtonAnalizar = new javax.swing.JButton();
        jButtonAbrir = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jPanelGeneral.setBackground(new java.awt.Color(142, 201, 219));
        jPanelGeneral.setLayout(new java.awt.BorderLayout());

        jPanelCentral.setOpaque(false);
        jPanelCentral.setLayout(new java.awt.GridLayout(1, 0));

        jPanel5.setForeground(new java.awt.Color(42, 56, 204));
        jPanel5.setOpaque(false);

        jScrollPane.setBorder(null);

        jTextAreaEdicion.setBackground(new java.awt.Color(204, 204, 204));
        jTextAreaEdicion.setColumns(20);
        jTextAreaEdicion.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jTextAreaEdicion.setRows(5);
        jTextAreaEdicion.setBorder(null);
        jTextAreaEdicion.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextAreaEdicionCaretUpdate(evt);
            }
        });
        jScrollPane.setViewportView(jTextAreaEdicion);

        jPanelResultados.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanelResultados.setLayout(new java.awt.GridLayout(1, 0));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addComponent(jPanelResultados, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanelResultados, javax.swing.GroupLayout.PREFERRED_SIZE, 786, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(179, 179, 179))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 749, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(216, 216, 216))))
        );

        jPanelCentral.add(jPanel5);

        jPanelGeneral.add(jPanelCentral, java.awt.BorderLayout.CENTER);

        jPanelSuperior.setOpaque(false);

        jPanelHeader.setBackground(new java.awt.Color(77, 98, 201));
        jPanelHeader.setForeground(new java.awt.Color(85, 128, 201));
        jPanelHeader.setOpaque(false);
        jPanelHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelBotones.setBackground(new java.awt.Color(0, 0, 0));
        jPanelBotones.setOpaque(false);
        jPanelBotones.setLayout(new javax.swing.BoxLayout(jPanelBotones, javax.swing.BoxLayout.LINE_AXIS));
        jPanelHeader.add(jPanelBotones, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, 40));

        jPanelBuscar.setBackground(new java.awt.Color(0, 153, 51));
        jPanelBuscar.setOpaque(false);
        jPanelBuscar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldBuscar.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanelBuscar.add(jTextFieldBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 200, 20));

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });
        jPanelBuscar.add(jButtonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 110, 20));

        jPanelHeader.add(jPanelBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, 340, 40));

        jButtonAnalizar.setText("Analizar");
        jButtonAnalizar.setPreferredSize(new java.awt.Dimension(72, 30));
        jButtonAnalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnalizarActionPerformed(evt);
            }
        });
        jPanelHeader.add(jButtonAnalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 100, -1));

        jButtonAbrir.setText("Abrir");
        jButtonAbrir.setPreferredSize(new java.awt.Dimension(72, 30));
        jButtonAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAbrirActionPerformed(evt);
            }
        });
        jPanelHeader.add(jButtonAbrir, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 80, -1));

        javax.swing.GroupLayout jPanelSuperiorLayout = new javax.swing.GroupLayout(jPanelSuperior);
        jPanelSuperior.setLayout(jPanelSuperiorLayout);
        jPanelSuperiorLayout.setHorizontalGroup(
            jPanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSuperiorLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jPanelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanelSuperiorLayout.setVerticalGroup(
            jPanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelHeader, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanelGeneral.add(jPanelSuperior, java.awt.BorderLayout.PAGE_START);

        jPanel4.setOpaque(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 965, Short.MAX_VALUE)
        );

        jPanelGeneral.add(jPanel4, java.awt.BorderLayout.LINE_END);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 1005, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1804, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        
        //Busqueda busqueda = new busqueda();
        
        if (jTextFieldBuscar.getText().isEmpty() || jTextAreaEdicion.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "NO HAY TEXTO PARA REALIZAR LA BUSQUEDA");
        } else {
            
            resultadoBusqueda pnlBusqueda = new resultadoBusqueda();
            pnlBusqueda.getjTextAreaBusqueda().append(jTextAreaEdicion.getText());
            pnlBusqueda.setVisible(true);
            
            busqueda.buscar(pnlBusqueda.getjTextAreaBusqueda(), jTextFieldBuscar.getText());
            jPanelResultados.removeAll();
            
            jPanelResultados.add(pnlBusqueda);
            jPanelResultados.repaint();
            jPanelResultados.revalidate();
        }
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAbrirActionPerformed
        ManejadorArchivos.abrirArchivos.abrirArchivo(this, jTextAreaEdicion);
    }//GEN-LAST:event_jButtonAbrirActionPerformed

    private void jButtonAnalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnalizarActionPerformed
        
        analizador.Analizar(jTextAreaEdicion.getText()+" ");
        manejarPaneles();
    }//GEN-LAST:event_jButtonAnalizarActionPerformed

    private void jTextAreaEdicionCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextAreaEdicionCaretUpdate
        int pos = evt.getDot(); //mira los pasos del puntero
//        try {
//            int fil = jTextArea1.getLineOfOffset(pos) + 1; //devuelve la fila
//            int col = pos - jTextArea1.getLineStartOffset(fil - 1) + 1; //devuelve la columna
//            this.jLabel5.setText(col + "");
//            this.jLabel3.setText(fil + "");
            actualizarNumeroFila();

//        } catch (BadLocationException exc) {
//            System.out.println(exc);
//        }
    }//GEN-LAST:event_jTextAreaEdicionCaretUpdate

   
    private void manejarPaneles() {
        
        jPanelResultados.removeAll();
        jPanelResultados.setOpaque(false);
        
        if ("".equals(jTextAreaEdicion.getText())) {
            JLabel label = new JLabel("Ingrese un texto para analizar", SwingConstants.CENTER);
            label.setForeground(Color.WHITE);
            label.setFont(new Font("Consolas",0, 18));
            jPanelResultados.add(label);
            
        } else if (analizador.getListaErrores().isEmpty()) {
            tokensLexemas pnlToken = new tokensLexemas(analizador.getListaTokens());
            pnlToken.setVisible(true);
            jPanelResultados.add(pnlToken);
            
        } else {
            errores pnlError = new errores(analizador.getListaErrores());
            pnlError.setVisible(true);
            jPanelResultados.add(pnlError);
            
        }
        
        jPanelResultados.repaint();
        jPanelResultados.revalidate();
    }
    
    int tFilas = 0;
    private void actualizarNumeroFila() {
            
            tFilas = jTextAreaEdicion.getLineCount();
            numeracionArea.setText("");
            for (int i = 0; i < tFilas; i++) {
                numeracionArea.append(" "+(i+1)+"\n");
            }

    }
    
    private JTextArea numeracionArea;
    
    private JTextArea mostrarNumeroFilas() {
        
        numeracionArea.setFont(new java.awt.Font("Consolas", 0, 14));
        numeracionArea.setBackground(new Color(108, 170, 208));
        numeracionArea.setForeground(Color.GRAY);        
        numeracionArea.setEditable(false);
        numeracionArea.append("1");
        
        return numeracionArea;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAbrir;
    private javax.swing.JButton jButtonAnalizar;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelBotones;
    private javax.swing.JPanel jPanelBuscar;
    private javax.swing.JPanel jPanelCentral;
    private javax.swing.JPanel jPanelGeneral;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JPanel jPanelResultados;
    private javax.swing.JPanel jPanelSuperior;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JTextArea jTextAreaEdicion;
    private javax.swing.JTextField jTextFieldBuscar;
    // End of variables declaration//GEN-END:variables

}
